# Generated by Django 3.1.4 on 2021-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='colorArea',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='colorText',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ColorArea',
        ),
        migrations.DeleteModel(
            name='ColorText',
        ),
    ]
